pipeline {
    agent any

    environment {
        // Set your environment variables
        DOCKER_REGISTRY = 'hub.docker.com'  // OR ECR Registry URL
        DOCKER_REPO = 'greet-app'
        CHART_NAME = 'greet-app'
        HELM_CHART_PATH = 'chart/greet-app'
        KUBE_NAMESPACE = 'default'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    // Your Docker build and push steps
                    docker.build("${DOCKER_REGISTRY}/${DOCKER_REPO}:${env.BUILD_NUMBER}")
                    docker.withRegistry("https://${DOCKER_REGISTRY}", 'docker-credentials') {
                        docker.image("${DOCKER_REGISTRY}/${DOCKER_REPO}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }

        stage('Deploy Helm Chart') {
            steps {
                script {
                    // Helm install or upgrade based on the release status
                    def releaseStatus = sh(script: "helm status ${CHART_NAME} --namespace=${KUBE_NAMESPACE}", returnStatus: true).trim()

                    if (releaseStatus == 0) {
                        echo "Helm chart already deployed. Updating..."
                        sh "helm upgrade --install ${CHART_NAME} ${HELM_CHART_PATH} --namespace=${KUBE_NAMESPACE} --set image.tag=${env.BUILD_NUMBER}"
                    } else {
                        echo "Deploying Helm chart for the first time..."
                        sh "helm install ${CHART_NAME} ${HELM_CHART_PATH} --namespace=${KUBE_NAMESPACE} --set image.tag=${env.BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}
